### ISSUE TITLE
No Wordpress bar for logged-in users appears on extra domains 

### ISSUE THREAD

**Issue by AndreaCensi** [straube/multiple-domain#13]
Hi,

The plugin works as intended, 

however the dashboard does not appear on the top for registered users.

Is there a way to fix this?

thanks!

**Comment by straube** [comment]
Hey @AndreaCensi! The plugin shouldn't change the top bar visibility. Have you tried to disable only the **multiple-domain** plugin to make sure it is causing the top bar to disappear?

**Comment by AndreaCensi** [comment]
Hi Gustavo,

I actually solved this - the problem was indeed with the multiple-domain
plugin, and the cause was that the cookies were not being passed correctly.

In the WP config, I changed `COOKIE_DOMAIN` to "domain.tld" instead of
"www.domain.tld" and now it works.

**Comment by straube** [comment]
I got it! That's actually due to a security measurement from WP. When a cookie is created, it sets a domain to it using the value from `COOKIE_DOMAIN`. In your case, the solution was simple because you use `domain.tld` and `www.domain.tld`, in other words, a domain and a subdomain. However, if you had two completely different domains with no common base, such as `somedomain.tld` and `anotherdomaon.tld`, this solution wouldn't work. I'll leave this issue open to see if I can figure out a way to have the plugin handling situations like this without impacting WP security.

Thanks for reporting that!

**Comment by straube** [comment]
I finally was able to do some research and the short answer is: this can't be fixed for different domains.

It's actually possible to use some technique to write the cookies in multiple domains, but it would require some ugly workarounds. Just like the one suggested in the first answer to this question: https://stackoverflow.com/q/19531183/1128918

I'm closing the issue for now.
