### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by averri** [straube/multiple-domain#3]
Error when activating the plugin:

```
Notice: Undefined index: host in /var/www/html/wp-content/plugins/multiple-domain/multiple-domain.php on line 212
```

**Comment by straube** [comment]
@averri It seems you're using the code from master. This issue was fixed on 0.3, please use that version ~~by getting the code from **0.3** branch~~.

If it's more convenient, you can also get the working version from [WordPress.org](https://wordpress.org/plugins/multiple-domain/) or by installing it from your WP Admin.

**UPDATE**: I've merged the latest updates into **master** branch and deleted 0.3.
