### ISSUE TITLE
Cannot activate the new updated plugin

### ISSUE THREAD

**Issue by classmate01** [straube/multiple-domain#53]
Error:
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/mysite/public_html/wp-content/plugins/multiple-domain/multiple-domain.php on line 39

**Comment by straube** [comment]
I guess you were using an older version of the plugin before the update, right? It's been a while since we don't support older PHP versions (< 5.6) and that error is probably because you're using 5.4 or 5.5. Is that right?

You have 3 options here:

1. Downgrade to an older version of MultipleDomain (0.8.6 is the most recent version that still supports PHP 5.5);
2. Upgrade your server to use a newer PHP version, preferably 7.1 or newer ([check this out](https://www.php.net/eol.php));
3. Change the plugin code, replacing all occurrences of `MultipleDomain::class` with `'MultipleDomain'` (string).

**Comment by classmate01** [comment]
where can I find a download link of the older version?
got it already thanks

**Comment by straube** [comment]
You may download it from the plugin page: https://wordpress.org/plugins/multiple-domain/advanced/. Look at **PREVIOUS VERSIONS** section at the end of the page.
