### ISSUE TITLE
Not working on WP 5.2.2

### ISSUE THREAD

**Issue by ysoldyoung87** [straube/multiple-domain#59]
Condition as below : 
WP installed at the sub directory of a domain 
e.g : [main domain] https://www.abc123.com
       [additional domain] https://www.abc123.com.sg
        [WP installed] https://www.abc123.com/blog/
        [WP installed] https://www.abc123.com.sg/blog/

Problem on Widget -> Posts list / Latest posts
The link at additional domain show wrongly as 
https://www.abc123.com.sg.sg/blog/[the-blog-topic]
Link was wrongly show double **.sg** in this case.

**Comment by straube** [comment]
I think this issue is not directly related to the WordPress version in question. Other users [reported](https://wordpress.org/support/topic/duplicate-second-level-domain/) [similar](https://wordpress.org/support/topic/domain-rewritten-wrongly/) [behavior](https://wordpress.org/support/topic/link-translation-wrong-domain/).

It seems that changing the order of domains in the plugin configuration fixes the error in some cases. It'd be better if the plugin handled these cases by its own instead of requiring users to enter the domains following some ordering criteria.
